
# This composition runs a full vdb instance with automatic service restarts,
# preconfigured for mainnet.
#
# When running you can access:
# postgres   @ localhost:5432
# graph(i)ql @ localhost:5000
#
# The client and database service stores the data on the *host* machine in a docker volume.
# This means that if the cluster is gracefully stopped, it can be restarted again
# without data loss.
#
# Commands:
# To start the cluster: `> docker-compose up`
# To stop the cluster, just `ctrl+c` (once, to allow a graceful exit)
# To reset the cluster: `docker-compose down --volumes` (after stopping the cluster)
#
# Note that it'll take a couple of days for the client to sync with thge network before
# vdb can do it's work.

version: "3.7"
services:
  header-sync:
    image: makerdao/vdb-headersync:latest # (needs wait-for-it.sh)
    environment:
      - CLIENT_IPCPATH=ws://geth-statediffing:8546
      - DATABASE_NAME=vdb
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_USER=vdb
      - DATABASE_PASSWORD=vdb
      - STARTING_BLOCK_NUMBER=8928152
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--strict", "--", "./startup_script.sh"]
    restart: unless-stopped

  extract-diffs:
    image: makerdao/vdb-extract-diffs:latest # (needs wait-for-it.sh)
    environment:
      # Remote client would need to be statediff enabled
      - CLIENT_IPCPATH=ws://geth-statediffing:8546
      - STORAGEDIFFS_SOURCE=geth
      - DATABASE_NAME=vdb
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_USER=vdb
      - DATABASE_PASSWORD=vdb
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--strict", "--", "./startup_script.sh"]

  execute:
    image: makerdao/vdb-execute:latest # (needs wait-for-it.sh)
    environment:
      - CLIENT_IPCPATH=ws://geth-statediffing:8546
      - DATABASE_NAME=vdb
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_USER=vdb
      - DATABASE_PASSWORD=vdb
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--strict", "--", "./startup_script.sh"]
    restart: unless-stopped

  db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vdb
      - POSTGRES_PASSWORD=vdb
    restart: always

  postgraphile:
    image: makerdao/vdb-postgraphile
    ports:
      - 5000:5000
    environment:
      - SCHEMAS=api,maker,public
      - DATABASE_URL=postgres://vdb:vdb@db:5432/vdb
    depends_on:
      - db
    restart: always

  # Optional in-cluster client. This will need to sync for a few days until you catch up with watched contracts
  geth-statediffing:
    image: makerdao/vdb-go-ethereum:latest
    ports:
      - 8545
      - 8546
      - 30303
    command: [
      "--verbosity", "2",
      "--rpc",
      "--rpcaddr", "0.0.0.0",
      "--ws",
      "--wsaddr", "0.0.0.0",
      "--statediff",
      "--syncmode", "full",
      # The following can be re-generated from another env file with:
      # awk -F= '/CONTRACT_.+_ADDRESS/{print "\"--statediff.watchedaddresses\", " "\""$2 "\", # " $1}' dockerfiles/mainnet-1.0.1.env
      "--statediff.watchedaddresses", "0x5ef30b9986345249bc32d8928b7ee64de9435e39", # CONTRACT_CDP_MANAGER_ADDRESS
      "--statediff.watchedaddresses", "0x78f2c2af65126834c51822f56be0d7469d7a523e", # CONTRACT_MCD_CAT_ADDRESS
      "--statediff.watchedaddresses", "0xdfe0fb1be2a52cdbf8fb962d5701d7fd0902db9f", # CONTRACT_MCD_FLAP_1.0.0_ADDRESS
      "--statediff.watchedaddresses", "0xC4269cC7acDEdC3794b221aA4D9205F564e27f0d", # CONTRACT_MCD_FLAP_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0xaA745404d55f88C108A28c86abE7b5A1E7817c07", # CONTRACT_MCD_FLIP_BAT_A_1.0.0_ADDRESS
      "--statediff.watchedaddresses", "0x5EdF770FC81E7b8C2c89f71F30f211226a4d7495", # CONTRACT_MCD_FLIP_BAT_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0xd8a04F5412223F513DC55F839574430f5EC15531", # CONTRACT_MCD_FLIP_ETH_A_1.0.0_ADDRESS
      "--statediff.watchedaddresses", "0x0F398a2DaAa134621e4b687FCcfeE4CE47599Cc1", # CONTRACT_MCD_FLIP_ETH_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0xAbBCB9Ae89cDD3C27E02D279480C7fF33083249b", # CONTRACT_MCD_FLIP_KNC_A_1.0.8_ADDRESS
      "--statediff.watchedaddresses", "0xAD4a0B5F3c6Deb13ADE106Ba6E80Ca6566538eE6", # CONTRACT_MCD_FLIP_KNC_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0x4bf9D2EBC4c57B9B783C12D30076507660B58b3a", # CONTRACT_MCD_FLIP_MANA_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0x5432b2f3c0DFf95AA191C45E5cbd539E2820aE72", # CONTRACT_MCD_FLIP_SAI_1.0.0_ADDRESS
      "--statediff.watchedaddresses", "0xba3f6a74BD12Cf1e48d4416c7b50963cA98AfD61", # CONTRACT_MCD_FLIP_TUSD_A_1.0.7_ADDRESS
      "--statediff.watchedaddresses", "0x04C42fAC3e29Fd27118609a5c36fD0b3Cb8090b3", # CONTRACT_MCD_FLIP_TUSD_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0xE6ed1d09a19Bd335f051d78D5d22dF3bfF2c28B1", # CONTRACT_MCD_FLIP_USDC_A_1.0.4_ADDRESS
      "--statediff.watchedaddresses", "0x545521e0105C5698f75D6b3C3050CfCC62FB0C12", # CONTRACT_MCD_FLIP_USDC_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0xec25Ca3fFa512afbb1784E17f1D414E16D01794F", # CONTRACT_MCD_FLIP_USDC_B_1.0.7_ADDRESS
      "--statediff.watchedaddresses", "0x6002d3B769D64A9909b0B26fC00361091786fe48", # CONTRACT_MCD_FLIP_USDC_B_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0x3E115d85D4d7253b05fEc9C0bB5b08383C2b0603", # CONTRACT_MCD_FLIP_WBTC_A_1.0.6_ADDRESS
      "--statediff.watchedaddresses", "0xF70590Fa4AaBe12d3613f5069D02B8702e058569", # CONTRACT_MCD_FLIP_WBTC_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0x08c89251FC058cC97d5bA5F06F95026C0A5CF9B0", # CONTRACT_MCD_FLIP_ZRX_A_1.0.8_ADDRESS
      "--statediff.watchedaddresses", "0x92645a34d07696395b6e5b8330b000D0436A9aAD", # CONTRACT_MCD_FLIP_ZRX_A_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0x4d95a049d5b0b7d32058cd3f2163015747522e99", # CONTRACT_MCD_FLOP_1.0.1_ADDRESS
      "--statediff.watchedaddresses", "0xA41B6EF151E06da0e34B009B86E828308986736D", # CONTRACT_MCD_FLOP_1.0.9_ADDRESS
      "--statediff.watchedaddresses", "0x19c0976f590d67707e62397c87829d896dc0f1f1", # CONTRACT_MCD_JUG_ADDRESS
      "--statediff.watchedaddresses", "0x197e90f9fad81970ba7976f33cbd77088e5d7cf7", # CONTRACT_MCD_POT_ADDRESS
      "--statediff.watchedaddresses", "0x65c79fcb50ca1594b025960e539ed7a9a6d434a3", # CONTRACT_MCD_SPOT_ADDRESS
      "--statediff.watchedaddresses", "0x35d1b3f3d7966a1dfe207aa4514c12a259a0492b", # CONTRACT_MCD_VAT_ADDRESS
      "--statediff.watchedaddresses", "0xa950524441892a31ebddf91d3ceefa04bf454466", # CONTRACT_MCD_VOW_ADDRESS
      "--statediff.watchedaddresses", "0x18B4633D6E39870f398597f3c1bA8c4A41294966", # CONTRACT_MEDIAN_BAT_ADDRESS
      "--statediff.watchedaddresses", "0x64DE91F5A373Cd4c28de3600cB34C7C6cE410C85", # CONTRACT_MEDIAN_ETH_ADDRESS
      "--statediff.watchedaddresses", "0x83076a2F42dc1925537165045c9FDe9A4B71AD97", # CONTRACT_MEDIAN_KNC_ADDRESS
      "--statediff.watchedaddresses", "0x681c4F8f69cF68852BAd092086ffEaB31F5B812c", # CONTRACT_MEDIAN_MANA_ADDRESS
      "--statediff.watchedaddresses", "0xe0F30cb149fAADC7247E953746Be9BbBB6B5751f", # CONTRACT_MEDIAN_WBTC_ADDRESS
      "--statediff.watchedaddresses", "0x956ecD6a9A9A0d84e8eB4e6BaaC09329E202E55e"  # CONTRACT_MEDIAN_ZRX_ADDRESS
    ]
    restart: unless-stopped
